### ISSUE TITLE
コメントに余分な空白が入る

### ISSUE THREAD

**Issue by h20y6m** [h-kitagawa/plistings#5]
以下のコードをタイプセットすると
```tex
\documentclass{jsarticle}
\usepackage{plistings}
\begin{document}
\begin{lstlisting}[language=C++]
/// コメント
/** コメント */
\end{lstlisting}
\end{document}
```
以下のようにコメント開始直後に余分な空白が入ります。
```
// / コメント
/* * コメント */
```

以下部分に行末のコメントアウトがないためのようです。
https://github.com/h-kitagawa/plistings/blob/983da47ef1cfc662945b590987948580bf459aed/plistings.sty#L338

**Comment by h-kitagawa** [comment]
どうもありがとうございます，直しました．
